name: Futurerestore

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: wget sed

      - name: Windows Build
        run: |
         wget https://raw.githubusercontent.com/dhinakg/futurerestore-compile-windows/3e64a150958308bade078a9b5088892c3d3ddcef/build.sh
         ./build.sh
         ls -lsall
      - name: futurerestore Linux x86_64 RELEASE Archive
        id: futurerestore-Linux-x86_64-RELEASE-Archive
        uses: actions/upload-artifact@v2
        with:
          name: futurerestore-Linux-x86_64-RELEASE
          path: |
            /home/runner/work/futurerestore/futurerestore/.github/workflows/futurerestore-Linux-x86_64*-RELEASE.tar.xz
      - name: futurerestore Linux x86_64 DEBUG Archive
        id: futurerestore-Linux-x86_64-DEBUG-Archive
        uses: actions/upload-artifact@v2
        with:
          name: futurerestore-Linux-x86_64-DEBUG
          path: |
            /home/runner/work/futurerestore/futurerestore/.github/workflows/futurerestore-Linux-x86_64*-DEBUG.tar.xz
